version: '2'
services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  database:
    image: postgres
    ports:
      - 33321:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: jaeger_db
  fullname-service:
    image: jaeger_playground
    build: .
    depends_on:
      - kafka
      - jaeger
    ports:
      - 8080:8080
    command: java -jar jaeger-playground.jar
  firstname-generator-service:
    image: jaeger_playground
    depends_on:
      - jaeger
    command: java -jar firstname-generator.jar
  lastname-generator-service:
    image: jaeger_playground
    depends_on:
      - jaeger
    command: java -jar lastname-generator.jar
  fullname-storage-service:
    image: jaeger_playground
    depends_on:
      - kafka
      - database
      - jaeger
    command: java -jar fullname-storage.jar
  fullnameapi-service:
    image: jaeger_playground
    depends_on:
      - database
      - jaeger
    ports:
      - 8081:8080
    command: java -jar fullnameapi.jar
