management:
  endpoints:
    web:
      exposure:
        include: info, health, state, beans, env, heapdump, loggers, metrics, mappings, threaddump, refresh, httptrace
service:
  firstname.url: http://firstname-generator-service:8080
  lastname.url: http://lastname-generator-service:8080
spring:
  application:
    name: full-name-service
  sleuth:
    opentracing:
      enabled: true
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://jaeger:9411
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest
logging:
  level:
    ru.reeson2003: debug
kafka.topic: full_names
