spring:
  datasource:
    url: jdbc:postgresql://database:5432/jaeger_db
    username: postgres
    password: test
  application:
    name: fullnameapi-service
  sleuth:
    opentracing:
      enabled: true
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://jaeger:9411
logging:
  level:
    ru.reeson2003: debug